// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgserver.proto

#ifndef PROTOBUF_msgserver_2eproto__INCLUDED
#define PROTOBUF_msgserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace NetProto {
class CSPNextData;
class CSPNextDataDefaultTypeInternal;
extern CSPNextDataDefaultTypeInternal _CSPNextData_default_instance_;
}  // namespace NetProto

namespace NetProto {

namespace protobuf_msgserver_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msgserver_2eproto

// ===================================================================

class CSPNextData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.CSPNextData) */ {
 public:
  CSPNextData();
  virtual ~CSPNextData();

  CSPNextData(const CSPNextData& from);

  inline CSPNextData& operator=(const CSPNextData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSPNextData(CSPNextData&& from) noexcept
    : CSPNextData() {
    *this = ::std::move(from);
  }

  inline CSPNextData& operator=(CSPNextData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSPNextData& default_instance();

  static inline const CSPNextData* internal_default_instance() {
    return reinterpret_cast<const CSPNextData*>(
               &_CSPNextData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CSPNextData* other);
  friend void swap(CSPNextData& a, CSPNextData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSPNextData* New() const PROTOBUF_FINAL { return New(NULL); }

  CSPNextData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CSPNextData& from);
  void MergeFrom(const CSPNextData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CSPNextData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 ivalue_arr = 4;
  int ivalue_arr_size() const;
  void clear_ivalue_arr();
  static const int kIvalueArrFieldNumber = 4;
  ::google::protobuf::int32 ivalue_arr(int index) const;
  void set_ivalue_arr(int index, ::google::protobuf::int32 value);
  void add_ivalue_arr(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ivalue_arr() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ivalue_arr();

  // repeated string svalue_arr = 5;
  int svalue_arr_size() const;
  void clear_svalue_arr();
  static const int kSvalueArrFieldNumber = 5;
  const ::std::string& svalue_arr(int index) const;
  ::std::string* mutable_svalue_arr(int index);
  void set_svalue_arr(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_svalue_arr(int index, ::std::string&& value);
  #endif
  void set_svalue_arr(int index, const char* value);
  void set_svalue_arr(int index, const char* value, size_t size);
  ::std::string* add_svalue_arr();
  void add_svalue_arr(const ::std::string& value);
  #if LANG_CXX11
  void add_svalue_arr(::std::string&& value);
  #endif
  void add_svalue_arr(const char* value);
  void add_svalue_arr(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& svalue_arr() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_svalue_arr();

  // optional string svalue = 3;
  bool has_svalue() const;
  void clear_svalue();
  static const int kSvalueFieldNumber = 3;
  const ::std::string& svalue() const;
  void set_svalue(const ::std::string& value);
  #if LANG_CXX11
  void set_svalue(::std::string&& value);
  #endif
  void set_svalue(const char* value);
  void set_svalue(const char* value, size_t size);
  ::std::string* mutable_svalue();
  ::std::string* release_svalue();
  void set_allocated_svalue(::std::string* svalue);

  // optional uint32 type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional int32 ivalue = 2;
  bool has_ivalue() const;
  void clear_ivalue();
  static const int kIvalueFieldNumber = 2;
  ::google::protobuf::int32 ivalue() const;
  void set_ivalue(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NetProto.CSPNextData)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_ivalue();
  void clear_has_ivalue();
  void set_has_svalue();
  void clear_has_svalue();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ivalue_arr_;
  ::google::protobuf::RepeatedPtrField< ::std::string> svalue_arr_;
  ::google::protobuf::internal::ArenaStringPtr svalue_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::int32 ivalue_;
  friend struct protobuf_msgserver_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CSPNextData

// optional uint32 type = 1;
inline bool CSPNextData::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSPNextData::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CSPNextData::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CSPNextData::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 CSPNextData::type() const {
  // @@protoc_insertion_point(field_get:NetProto.CSPNextData.type)
  return type_;
}
inline void CSPNextData::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.type)
}

// optional int32 ivalue = 2;
inline bool CSPNextData::has_ivalue() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSPNextData::set_has_ivalue() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CSPNextData::clear_has_ivalue() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CSPNextData::clear_ivalue() {
  ivalue_ = 0;
  clear_has_ivalue();
}
inline ::google::protobuf::int32 CSPNextData::ivalue() const {
  // @@protoc_insertion_point(field_get:NetProto.CSPNextData.ivalue)
  return ivalue_;
}
inline void CSPNextData::set_ivalue(::google::protobuf::int32 value) {
  set_has_ivalue();
  ivalue_ = value;
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.ivalue)
}

// optional string svalue = 3;
inline bool CSPNextData::has_svalue() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSPNextData::set_has_svalue() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSPNextData::clear_has_svalue() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSPNextData::clear_svalue() {
  svalue_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_svalue();
}
inline const ::std::string& CSPNextData::svalue() const {
  // @@protoc_insertion_point(field_get:NetProto.CSPNextData.svalue)
  return svalue_.GetNoArena();
}
inline void CSPNextData::set_svalue(const ::std::string& value) {
  set_has_svalue();
  svalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.svalue)
}
#if LANG_CXX11
inline void CSPNextData::set_svalue(::std::string&& value) {
  set_has_svalue();
  svalue_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NetProto.CSPNextData.svalue)
}
#endif
inline void CSPNextData::set_svalue(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_svalue();
  svalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NetProto.CSPNextData.svalue)
}
inline void CSPNextData::set_svalue(const char* value, size_t size) {
  set_has_svalue();
  svalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NetProto.CSPNextData.svalue)
}
inline ::std::string* CSPNextData::mutable_svalue() {
  set_has_svalue();
  // @@protoc_insertion_point(field_mutable:NetProto.CSPNextData.svalue)
  return svalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSPNextData::release_svalue() {
  // @@protoc_insertion_point(field_release:NetProto.CSPNextData.svalue)
  clear_has_svalue();
  return svalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSPNextData::set_allocated_svalue(::std::string* svalue) {
  if (svalue != NULL) {
    set_has_svalue();
  } else {
    clear_has_svalue();
  }
  svalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), svalue);
  // @@protoc_insertion_point(field_set_allocated:NetProto.CSPNextData.svalue)
}

// repeated int32 ivalue_arr = 4;
inline int CSPNextData::ivalue_arr_size() const {
  return ivalue_arr_.size();
}
inline void CSPNextData::clear_ivalue_arr() {
  ivalue_arr_.Clear();
}
inline ::google::protobuf::int32 CSPNextData::ivalue_arr(int index) const {
  // @@protoc_insertion_point(field_get:NetProto.CSPNextData.ivalue_arr)
  return ivalue_arr_.Get(index);
}
inline void CSPNextData::set_ivalue_arr(int index, ::google::protobuf::int32 value) {
  ivalue_arr_.Set(index, value);
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.ivalue_arr)
}
inline void CSPNextData::add_ivalue_arr(::google::protobuf::int32 value) {
  ivalue_arr_.Add(value);
  // @@protoc_insertion_point(field_add:NetProto.CSPNextData.ivalue_arr)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CSPNextData::ivalue_arr() const {
  // @@protoc_insertion_point(field_list:NetProto.CSPNextData.ivalue_arr)
  return ivalue_arr_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CSPNextData::mutable_ivalue_arr() {
  // @@protoc_insertion_point(field_mutable_list:NetProto.CSPNextData.ivalue_arr)
  return &ivalue_arr_;
}

// repeated string svalue_arr = 5;
inline int CSPNextData::svalue_arr_size() const {
  return svalue_arr_.size();
}
inline void CSPNextData::clear_svalue_arr() {
  svalue_arr_.Clear();
}
inline const ::std::string& CSPNextData::svalue_arr(int index) const {
  // @@protoc_insertion_point(field_get:NetProto.CSPNextData.svalue_arr)
  return svalue_arr_.Get(index);
}
inline ::std::string* CSPNextData::mutable_svalue_arr(int index) {
  // @@protoc_insertion_point(field_mutable:NetProto.CSPNextData.svalue_arr)
  return svalue_arr_.Mutable(index);
}
inline void CSPNextData::set_svalue_arr(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.svalue_arr)
  svalue_arr_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CSPNextData::set_svalue_arr(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:NetProto.CSPNextData.svalue_arr)
  svalue_arr_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CSPNextData::set_svalue_arr(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  svalue_arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:NetProto.CSPNextData.svalue_arr)
}
inline void CSPNextData::set_svalue_arr(int index, const char* value, size_t size) {
  svalue_arr_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NetProto.CSPNextData.svalue_arr)
}
inline ::std::string* CSPNextData::add_svalue_arr() {
  // @@protoc_insertion_point(field_add_mutable:NetProto.CSPNextData.svalue_arr)
  return svalue_arr_.Add();
}
inline void CSPNextData::add_svalue_arr(const ::std::string& value) {
  svalue_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:NetProto.CSPNextData.svalue_arr)
}
#if LANG_CXX11
inline void CSPNextData::add_svalue_arr(::std::string&& value) {
  svalue_arr_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:NetProto.CSPNextData.svalue_arr)
}
#endif
inline void CSPNextData::add_svalue_arr(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  svalue_arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:NetProto.CSPNextData.svalue_arr)
}
inline void CSPNextData::add_svalue_arr(const char* value, size_t size) {
  svalue_arr_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:NetProto.CSPNextData.svalue_arr)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CSPNextData::svalue_arr() const {
  // @@protoc_insertion_point(field_list:NetProto.CSPNextData.svalue_arr)
  return svalue_arr_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CSPNextData::mutable_svalue_arr() {
  // @@protoc_insertion_point(field_mutable_list:NetProto.CSPNextData.svalue_arr)
  return &svalue_arr_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgserver_2eproto__INCLUDED
