// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgtypeserver.proto

#ifndef PROTOBUF_msgtypeserver_2eproto__INCLUDED
#define PROTOBUF_msgtypeserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
namespace NetProto {
}  // namespace NetProto

namespace NetProto {

namespace protobuf_msgtypeserver_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msgtypeserver_2eproto

enum Net_G2F_MsgType {
  NET_G2F_Init = 0,
  NET_G2F_CreateRole = 1,
  Net_G2F_MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Net_G2F_MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Net_G2F_MsgType_IsValid(int value);
const Net_G2F_MsgType Net_G2F_MsgType_MIN = NET_G2F_Init;
const Net_G2F_MsgType Net_G2F_MsgType_MAX = NET_G2F_CreateRole;
const int Net_G2F_MsgType_ARRAYSIZE = Net_G2F_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Net_G2F_MsgType_descriptor();
inline const ::std::string& Net_G2F_MsgType_Name(Net_G2F_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Net_G2F_MsgType_descriptor(), value);
}
inline bool Net_G2F_MsgType_Parse(
    const ::std::string& name, Net_G2F_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Net_G2F_MsgType>(
    Net_G2F_MsgType_descriptor(), name, value);
}
enum Net_F2G_MsgType {
  NET_F2G_Init = 0,
  NET_F2G_CreateRole = 1,
  Net_F2G_MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Net_F2G_MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Net_F2G_MsgType_IsValid(int value);
const Net_F2G_MsgType Net_F2G_MsgType_MIN = NET_F2G_Init;
const Net_F2G_MsgType Net_F2G_MsgType_MAX = NET_F2G_CreateRole;
const int Net_F2G_MsgType_ARRAYSIZE = Net_F2G_MsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Net_F2G_MsgType_descriptor();
inline const ::std::string& Net_F2G_MsgType_Name(Net_F2G_MsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Net_F2G_MsgType_descriptor(), value);
}
inline bool Net_F2G_MsgType_Parse(
    const ::std::string& name, Net_F2G_MsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Net_F2G_MsgType>(
    Net_F2G_MsgType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace NetProto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::NetProto::Net_G2F_MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NetProto::Net_G2F_MsgType>() {
  return ::NetProto::Net_G2F_MsgType_descriptor();
}
template <> struct is_proto_enum< ::NetProto::Net_F2G_MsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NetProto::Net_F2G_MsgType>() {
  return ::NetProto::Net_F2G_MsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgtypeserver_2eproto__INCLUDED
